# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The&nbsp;Quest&nbsp;for the&nbsp;Game
description: >- # this means to ignore newlines until "baseurl:"
  2D top-down RPG game based on The&nbsp;Quest&nbsp;for&nbsp;Soda short film series
baseurl: "/the-quest-game" # the subpath of your site, e.g. /blog
url: "https://haframjolk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: haframjolk
github_username:  haframjolk
show_downloads: false
show_releases: true
default-lang: "en"
translations:
  en:
    doc-root:      "/"
    lang-name:     "English"
    lang-code:     "ğŸ‡ºğŸ‡¸"
    nav-github:    "View on GitHub"
    nav-download:  "Download"
    nav-downloads: "Downloads"
    menu:
      play:
        name:      "Play"
        url:       "/play/"
  is:
    doc-root:      "/is/"
    lang-name:     "Ãslenska"
    lang-code:     "ğŸ‡®ğŸ‡¸"
    nav-github:    "SkoÃ°a Ã¡ GitHub"
    nav-download:  "SÃ¦kja"
    nav-downloads: "NiÃ°urhal"
    description:   "TvÃ­vÃ­Ã°ur â€top-downâ€œ RPG leikur byggÃ°ur Ã¡ stuttmyndaserÃ­unni The&nbsp;Quest&nbsp;for&nbsp;Soda"
    menu:
      play:
        name:      "Spila"
        url:       "/is/play/"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
